from prometheus_client import Gauge, Counter, start_http_server

# Gauges
DATA_DRIFT_DETECTED = Gauge(
    "animal_classifier_data_drift_detected",
    "1 if data drift is detected, 0 otherwise"
)
DRIFTED_COLUMNS = Gauge(
    "animal_classifier_drifted_columns",
    "Number of columns detected as drifted"
)
PREDICTION_DRIFT_DETECTED = Gauge(
    "animal_classifier_prediction_drift_detected",
    "1 if prediction drift is detected, 0 otherwise"
)
MODEL_ACCURACY_CURRENT = Gauge(
    "animal_classifier_model_accuracy_current",
    "Current classification model accuracy"
)
MODEL_ACCURACY_REFERENCE = Gauge(
    "animal_classifier_model_accuracy_reference",
    "Reference classification model accuracy"
)

# Counter
ALERT_COUNT = Counter(
    "animal_classifier_alerts_total",
    "Cumulative number of alerts generated by monitoring"
)

def start_prometheus_server(port: int):
    start_http_server(port)
    print(f"🚀 Prometheus metrics available at http://localhost:{port}/metrics")
